apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: orp0dvi1z-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/orp0dvi1z-java-quarkus-gitops